/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXDatePicker;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Daniel Lindau
 */
public final class AgentPage extends javax.swing.JFrame {

    private final InfDB idb;
    private final Agent agent;

    /**
     * Creates new form AgentPage
     *
     * @param idb databaskopplingen
     * @param agent ett objekt av klassen Agent som representerar den agent som
     * loggat in.
     */
    public AgentPage(InfDB idb, Agent agent) {
        initComponents();
        this.idb = idb;
        this.agent = agent;
        lblValkommen.setText("Inloggad som: " + agent.getNamn() + ".");
        this.setLocationRelativeTo(null);
        pnlHuvudMeny.setVisible(true);
        pnlAlienMeny.setVisible(false);
        pnlAlienRegistrering.setVisible(false);

        //pnlAgentmeny.setVisible(false);
        //pnlUtrustningMeny.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblAgentLogo = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        lblMeny = new javax.swing.JLabel();
        pnlHuvudMeny = new javax.swing.JPanel();
        lblLoggaUt = new javax.swing.JLabel();
        lblAndraLosen = new javax.swing.JLabel();
        lblAgenter = new javax.swing.JLabel();
        lblAliens = new javax.swing.JLabel();
        lblUtrustning = new javax.swing.JLabel();
        pnlAlienMeny = new javax.swing.JPanel();
        lblTillbaka = new javax.swing.JLabel();
        lblSok = new javax.swing.JLabel();
        lblRegistrera = new javax.swing.JLabel();
        lblListaAlla = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlAlienRegistrering = new javax.swing.JPanel();
        lblNamn = new javax.swing.JLabel();
        txtAlienNamn = new javax.swing.JTextField();
        txtAlienTelefon = new javax.swing.JTextField();
        lblLosenord = new javax.swing.JLabel();
        jXDateAnkomstDatum = new org.jdesktop.swingx.JXDatePicker();
        lblAnkomstDatum = new javax.swing.JLabel();
        txtAlienLosenord = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        lblRegistreraTitel = new javax.swing.JLabel();
        jcbAlienPlats = new javax.swing.JComboBox<>();
        lblPlats = new javax.swing.JLabel();
        jcbAnsvarigAgent = new javax.swing.JComboBox<>();
        lblAnsvarigAgent = new javax.swing.JLabel();
        btnSparaAlien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 475));
        setPreferredSize(new java.awt.Dimension(800, 475));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(29, 29, 48));
        pnlBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlBackground.setLayout(null);

        lblAgentLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/headicon.png"))); // NOI18N
        pnlBackground.add(lblAgentLogo);
        lblAgentLogo.setBounds(30, 20, 41, 80);

        lblValkommen.setForeground(new java.awt.Color(204, 204, 204));
        lblValkommen.setText("Inloggad");
        pnlBackground.add(lblValkommen);
        lblValkommen.setBounds(30, 100, 90, 40);

        lblMeny.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMeny.setForeground(new java.awt.Color(204, 204, 204));
        lblMeny.setText("MENY");
        pnlBackground.add(lblMeny);
        lblMeny.setBounds(30, 290, 41, 16);

        pnlHuvudMeny.setBackground(new java.awt.Color(29, 29, 48));
        pnlHuvudMeny.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlHuvudMeny.setMinimumSize(new java.awt.Dimension(150, 200));
        pnlHuvudMeny.setPreferredSize(new java.awt.Dimension(150, 200));
        pnlHuvudMeny.setLayout(null);

        lblLoggaUt.setForeground(new java.awt.Color(204, 204, 204));
        lblLoggaUt.setText("Logga ut");
        lblLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoggaUtMouseClicked(evt);
            }
        });
        pnlHuvudMeny.add(lblLoggaUt);
        lblLoggaUt.setBounds(10, 90, 100, 20);

        lblAndraLosen.setForeground(new java.awt.Color(204, 204, 204));
        lblAndraLosen.setText("Ändra lösenord");
        lblAndraLosen.setMaximumSize(new java.awt.Dimension(50, 15));
        lblAndraLosen.setMinimumSize(new java.awt.Dimension(50, 15));
        lblAndraLosen.setPreferredSize(new java.awt.Dimension(50, 15));
        lblAndraLosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAndraLosenMouseClicked(evt);
            }
        });
        pnlHuvudMeny.add(lblAndraLosen);
        lblAndraLosen.setBounds(10, 70, 100, 20);

        lblAgenter.setForeground(new java.awt.Color(204, 204, 204));
        lblAgenter.setText("Agenter");
        pnlHuvudMeny.add(lblAgenter);
        lblAgenter.setBounds(10, 10, 100, 20);

        lblAliens.setForeground(new java.awt.Color(204, 204, 204));
        lblAliens.setText("Aliens");
        lblAliens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAliensMouseClicked(evt);
            }
        });
        pnlHuvudMeny.add(lblAliens);
        lblAliens.setBounds(10, 30, 100, 20);

        lblUtrustning.setForeground(new java.awt.Color(204, 204, 204));
        lblUtrustning.setText("Utrustning");
        pnlHuvudMeny.add(lblUtrustning);
        lblUtrustning.setBounds(10, 50, 100, 20);

        pnlBackground.add(pnlHuvudMeny);
        pnlHuvudMeny.setBounds(20, 310, 120, 120);

        pnlAlienMeny.setBackground(new java.awt.Color(29, 29, 48));
        pnlAlienMeny.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlAlienMeny.setMinimumSize(new java.awt.Dimension(150, 200));
        pnlAlienMeny.setLayout(null);

        lblTillbaka.setForeground(new java.awt.Color(204, 204, 204));
        lblTillbaka.setText("Tillbaka");
        lblTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTillbakaMouseClicked(evt);
            }
        });
        pnlAlienMeny.add(lblTillbaka);
        lblTillbaka.setBounds(10, 80, 100, 20);

        lblSok.setForeground(new java.awt.Color(204, 204, 204));
        lblSok.setText("Sök och ändra");
        lblSok.setMaximumSize(new java.awt.Dimension(50, 15));
        lblSok.setMinimumSize(new java.awt.Dimension(50, 15));
        lblSok.setPreferredSize(new java.awt.Dimension(50, 15));
        lblSok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSokMouseClicked(evt);
            }
        });
        pnlAlienMeny.add(lblSok);
        lblSok.setBounds(10, 40, 100, 20);

        lblRegistrera.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistrera.setText("Regístrera ny");
        lblRegistrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistreraMouseClicked(evt);
            }
        });
        pnlAlienMeny.add(lblRegistrera);
        lblRegistrera.setBounds(10, 20, 100, 20);

        lblListaAlla.setForeground(new java.awt.Color(204, 204, 204));
        lblListaAlla.setText("Lista alla");
        pnlAlienMeny.add(lblListaAlla);
        lblListaAlla.setBounds(10, 60, 100, 20);

        pnlBackground.add(pnlAlienMeny);
        pnlAlienMeny.setBounds(20, 310, 120, 120);

        pnlMain.setBackground(new java.awt.Color(29, 29, 48));
        pnlMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlMain.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pnlBackground.add(pnlMain);
        pnlMain.setBounds(160, 20, 620, 410);

        pnlAlienRegistrering.setBackground(new java.awt.Color(29, 29, 48));
        pnlAlienRegistrering.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlAlienRegistrering.setForeground(new java.awt.Color(204, 204, 204));
        pnlAlienRegistrering.setLayout(null);

        lblNamn.setForeground(new java.awt.Color(204, 204, 204));
        lblNamn.setText("Namn:");
        pnlAlienRegistrering.add(lblNamn);
        lblNamn.setBounds(20, 60, 36, 16);
        pnlAlienRegistrering.add(txtAlienNamn);
        txtAlienNamn.setBounds(120, 60, 100, 24);
        pnlAlienRegistrering.add(txtAlienTelefon);
        txtAlienTelefon.setBounds(120, 90, 100, 24);

        lblLosenord.setForeground(new java.awt.Color(204, 204, 204));
        lblLosenord.setText("Lösenord:");
        pnlAlienRegistrering.add(lblLosenord);
        lblLosenord.setBounds(20, 120, 70, 16);
        pnlAlienRegistrering.add(jXDateAnkomstDatum);
        jXDateAnkomstDatum.setBounds(120, 210, 141, 24);

        lblAnkomstDatum.setForeground(new java.awt.Color(204, 204, 204));
        lblAnkomstDatum.setText("Ankomstdatum:");
        pnlAlienRegistrering.add(lblAnkomstDatum);
        lblAnkomstDatum.setBounds(20, 210, 90, 16);
        pnlAlienRegistrering.add(txtAlienLosenord);
        txtAlienLosenord.setBounds(120, 120, 100, 24);

        lblTelefon.setForeground(new java.awt.Color(204, 204, 204));
        lblTelefon.setText("Telefon:");
        pnlAlienRegistrering.add(lblTelefon);
        lblTelefon.setBounds(20, 90, 50, 16);

        lblRegistreraTitel.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblRegistreraTitel.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistreraTitel.setText("Registrera ny alien");
        pnlAlienRegistrering.add(lblRegistreraTitel);
        lblRegistreraTitel.setBounds(20, 10, 180, 40);

        pnlAlienRegistrering.add(jcbAlienPlats);
        jcbAlienPlats.setBounds(120, 150, 120, 26);

        lblPlats.setForeground(new java.awt.Color(204, 204, 204));
        lblPlats.setText("Plats:");
        pnlAlienRegistrering.add(lblPlats);
        lblPlats.setBounds(20, 150, 60, 16);

        pnlAlienRegistrering.add(jcbAnsvarigAgent);
        jcbAnsvarigAgent.setBounds(120, 180, 120, 26);

        lblAnsvarigAgent.setForeground(new java.awt.Color(204, 204, 204));
        lblAnsvarigAgent.setText("Ansvarig agent:");
        pnlAlienRegistrering.add(lblAnsvarigAgent);
        lblAnsvarigAgent.setBounds(20, 180, 88, 16);

        btnSparaAlien.setText("Spara");
        btnSparaAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSparaAlienMouseClicked(evt);
            }
        });
        pnlAlienRegistrering.add(btnSparaAlien);
        btnSparaAlien.setBounds(140, 240, 90, 32);

        pnlBackground.add(pnlAlienRegistrering);
        pnlAlienRegistrering.setBounds(160, 20, 620, 410);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggaUtMouseClicked

        if (Validering.kollaUtloggning()) {
            this.dispose();
            new MainPage(idb).setVisible(true);
        }

    }//GEN-LAST:event_lblLoggaUtMouseClicked

    private void lblAndraLosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAndraLosenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAndraLosenMouseClicked

    private void lblSokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSokMouseClicked

    private void lblAliensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAliensMouseClicked
        pnlHuvudMeny.setVisible(false);
        pnlAlienMeny.setVisible(true);
    }//GEN-LAST:event_lblAliensMouseClicked

    private void lblTillbakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTillbakaMouseClicked
        pnlHuvudMeny.setVisible(true);
        pnlAlienMeny.setVisible(false);
    }//GEN-LAST:event_lblTillbakaMouseClicked

    private void lblRegistreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistreraMouseClicked
        pnlMain.setVisible(false);
        pnlAlienRegistrering.setVisible(true);
        jcbAlienPlats.removeAllItems();
        jcbAnsvarigAgent.removeAllItems();
        fyllComboBox(jcbAlienPlats, "PLATS_ID", "BENAMNING", "PLATS");
        fyllComboBox(jcbAnsvarigAgent, "AGENT_ID", "NAMN", "AGENT");
        jXDateAnkomstDatum.getEditor().setEditable(false);
        Date dagensDatum = new Date();
        jXDateAnkomstDatum.setDate(dagensDatum);

    }//GEN-LAST:event_lblRegistreraMouseClicked

    private void btnSparaAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparaAlienMouseClicked

        sparaAlien();

    }//GEN-LAST:event_btnSparaAlienMouseClicked

    /**
     * Den här metoden används för att fylla på med värden till comboboxar
     * 
     * 
     * @param jcb ComboBoxen som ska få värden
     * @param kolumn1 första kolumnen
     * @param kolumn2 andra kolumnen
     * @param tabell från vilken databastabell ska kolumnerna hämtas.
     *
     */
    public void fyllComboBox(JComboBox jcb, String kolumn1, String kolumn2, String tabell) {
        String sokStrang = "select " + kolumn1 + ", " + kolumn2 + " from " + tabell;
        try {
            ArrayList<HashMap<String, String>> allaObjekt = idb.fetchRows(sokStrang);
            String item;
            for (HashMap<String, String> ettObjekt : allaObjekt) {
                item = ettObjekt.get(kolumn1) + " " + ettObjekt.get(kolumn2);
                jcb.addItem(item);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Det gick inte att hämta värden till comboboxen");
        }
    }

    public String getFranComboBox(JComboBox jcb, int n) {

        String item[] = jcb.getSelectedItem().toString().split(" ");
        String svar = item[n];

        return svar;
    }

    public void sparaAlien() {

        String namn = txtAlienNamn.getText();
        String telefon = txtAlienTelefon.getText();
        String losenord = txtAlienLosenord.getText();
        String plats = getFranComboBox(jcbAlienPlats, 0);
        String ansvarigAgent = getFranComboBox(jcbAnsvarigAgent, 0);
        String datum = getDatum(jXDateAnkomstDatum);

        if (Validering.kollaTextRutaTom(txtAlienNamn)
                && Validering.kollaTextRutaTom(txtAlienTelefon)
                && Validering.kollaTextRutaTom(txtAlienLosenord)) {

            try {
                int nextIndex = Integer.parseInt(idb.getAutoIncrement("ALIEN", "ALIEN_ID"));

                String insert = "insert into ALIEN values (" + nextIndex + ", '" + datum + "', " + "'" + losenord + "', " + "'" + namn + "', " + "'" + telefon + "', " + plats + ", " + ansvarigAgent + ")";
                System.out.println(insert);
                idb.insert(insert);
                JOptionPane.showMessageDialog(null, "Alien sparad");
                txtAlienNamn.setText(null);
                txtAlienTelefon.setText(null);
                txtAlienLosenord.setText(null);

            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Det gick inte att spara.");
            }

        }
    }

    public String getDatum(JXDatePicker jXD) {
        Date valtDatum = jXD.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String datum = dateFormat.format(valtDatum);
        return datum;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAlien;
    private org.jdesktop.swingx.JXDatePicker jXDateAnkomstDatum;
    private javax.swing.JComboBox<String> jcbAlienPlats;
    private javax.swing.JComboBox<String> jcbAnsvarigAgent;
    private javax.swing.JLabel lblAgentLogo;
    private javax.swing.JLabel lblAgenter;
    private javax.swing.JLabel lblAliens;
    private javax.swing.JLabel lblAndraLosen;
    private javax.swing.JLabel lblAnkomstDatum;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblListaAlla;
    private javax.swing.JLabel lblLoggaUt;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblMeny;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JLabel lblRegistrera;
    private javax.swing.JLabel lblRegistreraTitel;
    private javax.swing.JLabel lblSok;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTillbaka;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JPanel pnlAlienMeny;
    private javax.swing.JPanel pnlAlienRegistrering;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHuvudMeny;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtAlienLosenord;
    private javax.swing.JTextField txtAlienNamn;
    private javax.swing.JTextField txtAlienTelefon;
    // End of variables declaration//GEN-END:variables
}
