/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import oru.inf.InfDB;

/**
 *
 * @author Daniel Lindau
 */
public class AgentPage extends javax.swing.JFrame {

    private final InfDB idb;
    private final Agent agent;

    /**
     * Creates new form AgentPage
     *
     * @param idb databaskopplingen
     * @param agent ett objekt av klassen Agent som representerar den agent som
     * loggat in.
     */
    public AgentPage(InfDB idb, Agent agent) {
        initComponents();
        this.idb = idb;
        this.agent = agent;
        lblValkommen.setText("Inloggad som: " + agent.getNamn() + ".");
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlAgentInfo = new javax.swing.JPanel();
        pnlMeny = new javax.swing.JPanel();
        lblLoggaUt = new javax.swing.JLabel();
        lblAndraLosen = new javax.swing.JLabel();
        lblAgenter = new javax.swing.JLabel();
        lblAliens = new javax.swing.JLabel();
        lblUtrustning = new javax.swing.JLabel();
        lblMeny = new javax.swing.JLabel();
        lblAgentLogo = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 475));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(29, 29, 48));
        pnlBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlBackground.setLayout(null);

        pnlAgentInfo.setBackground(new java.awt.Color(29, 29, 48));
        pnlAgentInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout pnlAgentInfoLayout = new javax.swing.GroupLayout(pnlAgentInfo);
        pnlAgentInfo.setLayout(pnlAgentInfoLayout);
        pnlAgentInfoLayout.setHorizontalGroup(
            pnlAgentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        pnlAgentInfoLayout.setVerticalGroup(
            pnlAgentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pnlBackground.add(pnlAgentInfo);
        pnlAgentInfo.setBounds(160, 20, 620, 410);

        pnlMeny.setBackground(new java.awt.Color(29, 29, 48));
        pnlMeny.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlMeny.setMinimumSize(new java.awt.Dimension(150, 200));
        pnlMeny.setPreferredSize(new java.awt.Dimension(150, 200));
        pnlMeny.setLayout(null);

        lblLoggaUt.setForeground(new java.awt.Color(204, 204, 204));
        lblLoggaUt.setText("Logga ut");
        lblLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoggaUtMouseClicked(evt);
            }
        });
        pnlMeny.add(lblLoggaUt);
        lblLoggaUt.setBounds(10, 110, 100, 20);

        lblAndraLosen.setForeground(new java.awt.Color(204, 204, 204));
        lblAndraLosen.setText("Ändra lösenord");
        lblAndraLosen.setMaximumSize(new java.awt.Dimension(50, 15));
        lblAndraLosen.setMinimumSize(new java.awt.Dimension(50, 15));
        lblAndraLosen.setPreferredSize(new java.awt.Dimension(50, 15));
        lblAndraLosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAndraLosenMouseClicked(evt);
            }
        });
        pnlMeny.add(lblAndraLosen);
        lblAndraLosen.setBounds(10, 90, 100, 20);

        lblAgenter.setText("Agenter");
        pnlMeny.add(lblAgenter);
        lblAgenter.setBounds(10, 30, 100, 20);

        lblAliens.setText("Aliens");
        pnlMeny.add(lblAliens);
        lblAliens.setBounds(10, 50, 100, 20);

        lblUtrustning.setText("Utrustning");
        pnlMeny.add(lblUtrustning);
        lblUtrustning.setBounds(10, 70, 100, 20);

        lblMeny.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMeny.setText("MENY");
        pnlMeny.add(lblMeny);
        lblMeny.setBounds(10, 10, 41, 16);

        pnlBackground.add(pnlMeny);
        pnlMeny.setBounds(20, 140, 120, 140);

        lblAgentLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/headicon.png"))); // NOI18N
        pnlBackground.add(lblAgentLogo);
        lblAgentLogo.setBounds(30, 20, 41, 80);

        lblValkommen.setForeground(new java.awt.Color(204, 204, 204));
        lblValkommen.setText("Inloggad");
        pnlBackground.add(lblValkommen);
        lblValkommen.setBounds(30, 100, 90, 40);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggaUtMouseClicked

        if (Validering.kollaUtloggning()) {
            this.dispose();
            new MainPage(idb).setVisible(true);
        }

    }//GEN-LAST:event_lblLoggaUtMouseClicked

    private void lblAndraLosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAndraLosenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAndraLosenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAgentLogo;
    private javax.swing.JLabel lblAgenter;
    private javax.swing.JLabel lblAliens;
    private javax.swing.JLabel lblAndraLosen;
    private javax.swing.JLabel lblLoggaUt;
    private javax.swing.JLabel lblMeny;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JPanel pnlAgentInfo;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlMeny;
    // End of variables declaration//GEN-END:variables
}
