/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import oru.inf.InfDB;

/**
 *
 * @author Daniel
 */
public class AlienPage extends javax.swing.JFrame {

    private final InfDB idb;
    private Alien alien;
    //private boolean inloggad;

    /**
     * Creates new form AlienPage
     * @param idb databaskopplingen
     * @param alien den alien som har loggat in.
     */
    public AlienPage(InfDB idb, Alien alien) {
        initComponents();
        this.idb = idb;
        this.alien = alien;
       // inloggad = true;
        lblValkommen.setText("Välkommen " + alien.getNamn() + "! Vad vill du göra idag?");
        this.setLocationRelativeTo(null);
        
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblLogoHolder = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        lblSok = new javax.swing.JLabel();
        lblKontakt = new javax.swing.JLabel();
        lblAndraLosen = new javax.swing.JLabel();
        lblLoggaUt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 475));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(29, 29, 48));
        pnlBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlBackground.setLayout(null);

        lblLogoHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/alienicon.png"))); // NOI18N
        pnlBackground.add(lblLogoHolder);
        lblLogoHolder.setBounds(30, 10, 70, 100);

        lblValkommen.setForeground(new java.awt.Color(204, 204, 204));
        lblValkommen.setText("Välkommen... Vad vill du göra idag?");
        pnlBackground.add(lblValkommen);
        lblValkommen.setBounds(110, 50, 200, 16);

        lblSok.setForeground(new java.awt.Color(204, 204, 204));
        lblSok.setText("Sök Aliens");
        lblSok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSokMouseClicked(evt);
            }
        });
        pnlBackground.add(lblSok);
        lblSok.setBounds(30, 200, 150, 16);

        lblKontakt.setForeground(new java.awt.Color(204, 204, 204));
        lblKontakt.setText("Kontakta din områdeschef");
        pnlBackground.add(lblKontakt);
        lblKontakt.setBounds(30, 250, 160, 16);

        lblAndraLosen.setForeground(new java.awt.Color(204, 204, 204));
        lblAndraLosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/passwordicon.png"))); // NOI18N
        lblAndraLosen.setText("   Ändra lösenord");
        lblAndraLosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAndraLosenMouseClicked(evt);
            }
        });
        pnlBackground.add(lblAndraLosen);
        lblAndraLosen.setBounds(30, 290, 150, 50);

        lblLoggaUt.setForeground(new java.awt.Color(204, 204, 204));
        lblLoggaUt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/logouticon.png"))); // NOI18N
        lblLoggaUt.setText("   Logga ut");
        lblLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoggaUtMouseClicked(evt);
            }
        });
        pnlBackground.add(lblLoggaUt);
        lblLoggaUt.setBounds(30, 350, 120, 50);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggaUtMouseClicked
        // TODO add your handling code here:
        if(Validering.kollaUtloggning()){
        setVisible(false);
        new MainPage(idb).setVisible(true);
        }
        
    }//GEN-LAST:event_lblLoggaUtMouseClicked

    private void lblAndraLosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAndraLosenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAndraLosenMouseClicked

    private void lblSokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSokMouseClicked
        // TODO add your handling code here:
        
        String namn = alien.getNamn();
        System.out.println(namn);
        
    }//GEN-LAST:event_lblSokMouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAndraLosen;
    private javax.swing.JLabel lblKontakt;
    private javax.swing.JLabel lblLoggaUt;
    private javax.swing.JLabel lblLogoHolder;
    private javax.swing.JLabel lblSok;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
