/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import oru.inf.InfDB;

/**
 *
 * @author Daniel
 */
public class AlienPage extends javax.swing.JFrame {

    private final InfDB idb;
    private Alien alien;
    //private boolean inloggad;

    /**
     * Creates new form AlienPage
     * @param idb databaskopplingen
     * @param alien den alien som har loggat in.
     */
    public AlienPage(InfDB idb, Alien alien) {
        initComponents();
        this.idb = idb;
        this.alien = alien;
       // inloggad = true;
        lblValkommen.setText("VÃ¤lkommen " + alien.getNamn() + "! Vad vill du gÃ¶ra idag?");
        this.setLocationRelativeTo(null);
        
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblLogoHolder = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        pnlHuvudMenyAlien = new javax.swing.JPanel();
        lblLoggaUt1 = new javax.swing.JLabel();
        lblAndraLosen1 = new javax.swing.JLabel();
        lblAgenter = new javax.swing.JLabel();
        lblAliens = new javax.swing.JLabel();
        lblMeny = new javax.swing.JLabel();
        pnlAgentInfo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 475));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(29, 29, 48));
        pnlBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlBackground.setLayout(null);

        lblLogoHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/alienicon.png"))); // NOI18N
        pnlBackground.add(lblLogoHolder);
        lblLogoHolder.setBounds(30, 10, 70, 100);

        lblValkommen.setForeground(new java.awt.Color(204, 204, 204));
        lblValkommen.setText("Välkommen... ");
        pnlBackground.add(lblValkommen);
        lblValkommen.setBounds(30, 120, 90, 16);

        pnlHuvudMenyAlien.setBackground(new java.awt.Color(29, 29, 48));
        pnlHuvudMenyAlien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlHuvudMenyAlien.setMinimumSize(new java.awt.Dimension(150, 200));
        pnlHuvudMenyAlien.setLayout(null);

        lblLoggaUt1.setForeground(new java.awt.Color(204, 204, 204));
        lblLoggaUt1.setText("Logga ut");
        lblLoggaUt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoggaUt1MouseClicked(evt);
            }
        });
        pnlHuvudMenyAlien.add(lblLoggaUt1);
        lblLoggaUt1.setBounds(10, 110, 100, 20);

        lblAndraLosen1.setForeground(new java.awt.Color(204, 204, 204));
        lblAndraLosen1.setText("Ändra lösenord");
        lblAndraLosen1.setMaximumSize(new java.awt.Dimension(50, 15));
        lblAndraLosen1.setMinimumSize(new java.awt.Dimension(50, 15));
        lblAndraLosen1.setPreferredSize(new java.awt.Dimension(50, 15));
        lblAndraLosen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAndraLosen1MouseClicked(evt);
            }
        });
        pnlHuvudMenyAlien.add(lblAndraLosen1);
        lblAndraLosen1.setBounds(10, 90, 100, 20);

        lblAgenter.setForeground(new java.awt.Color(204, 204, 204));
        lblAgenter.setText("Kontakta agent");
        pnlHuvudMenyAlien.add(lblAgenter);
        lblAgenter.setBounds(10, 70, 100, 20);

        lblAliens.setForeground(new java.awt.Color(204, 204, 204));
        lblAliens.setText("Sök andra aliens");
        pnlHuvudMenyAlien.add(lblAliens);
        lblAliens.setBounds(10, 50, 100, 20);

        lblMeny.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMeny.setForeground(new java.awt.Color(204, 204, 204));
        lblMeny.setText("MENY");
        pnlHuvudMenyAlien.add(lblMeny);
        lblMeny.setBounds(10, 10, 41, 16);

        pnlBackground.add(pnlHuvudMenyAlien);
        pnlHuvudMenyAlien.setBounds(20, 290, 120, 140);

        pnlAgentInfo.setBackground(new java.awt.Color(29, 29, 48));
        pnlAgentInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout pnlAgentInfoLayout = new javax.swing.GroupLayout(pnlAgentInfo);
        pnlAgentInfo.setLayout(pnlAgentInfoLayout);
        pnlAgentInfoLayout.setHorizontalGroup(
            pnlAgentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        pnlAgentInfoLayout.setVerticalGroup(
            pnlAgentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pnlBackground.add(pnlAgentInfo);
        pnlAgentInfo.setBounds(160, 20, 620, 410);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggaUt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggaUt1MouseClicked

        if (Validering.kollaUtloggning()) {
            this.dispose();
            new MainPage(idb).setVisible(true);
        }
    }//GEN-LAST:event_lblLoggaUt1MouseClicked

    private void lblAndraLosen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAndraLosen1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAndraLosen1MouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAgenter;
    private javax.swing.JLabel lblAliens;
    private javax.swing.JLabel lblAndraLosen1;
    private javax.swing.JLabel lblLoggaUt1;
    private javax.swing.JLabel lblLogoHolder;
    private javax.swing.JLabel lblMeny;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JPanel pnlAgentInfo;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHuvudMenyAlien;
    // End of variables declaration//GEN-END:variables
}
