/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Daniel
 */
public class HuvudFonster extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form HuvudFonster
     *
     * @param idb databaskopplingen
     */
    public HuvudFonster(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblLogoHolder = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 475));
        setSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("MIB SEKTOR SKANDINAVIEN");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(120, 260, 160, 22);

        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("Användarnamn:");
        getContentPane().add(lblUser);
        lblUser.setBounds(70, 320, 100, 16);

        lblPass.setForeground(new java.awt.Color(204, 204, 204));
        lblPass.setText("Lösenord:");
        lblPass.setAlignmentY(0.0F);
        getContentPane().add(lblPass);
        lblPass.setBounds(70, 350, 80, 16);
        getContentPane().add(txtUserName);
        txtUserName.setBounds(210, 320, 110, 24);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(210, 350, 110, 24);

        btnLogin.setText("Logga in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(230, 380, 90, 32);

        lblLogoHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/head.png"))); // NOI18N
        lblLogoHolder.setPreferredSize(new java.awt.Dimension(150, 300));
        getContentPane().add(lblLogoHolder);
        lblLogoHolder.setBounds(120, 0, 150, 300);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/bg2.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        if (Validering.kollaTextRutaTom(txtUserName) && Validering.kollaHeltal(txtUserName)) {

            try {
                String userID = txtUserName.getText();
                String password = txtPassword.getText();
                String pass = idb.fetchSingle("select LOSENORD from AGENT where AGENT_ID = " + userID);
                String userName = idb.fetchSingle("select NAMN from AGENT where AGENT_ID = " + userID);
                if (pass.equals(password)) {
                    JOptionPane.showMessageDialog(null, "Välkommen " + userName + ". Du har nu loggat in");
                    //setVisible(false); //Gömmer inloggningsfönstret

                    //lägg metodanrop för nästa fönster här.
                } else {
                    JOptionPane.showMessageDialog(null, "Fel lösenord, försök igen");
                    txtPassword.requestFocusInWindow();
                }

            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något gick fel");
            }

        }

    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogoHolder;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
