/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Daniel Lindau
 * @version 0.1b
 *
 */
public class LoginForm extends javax.swing.JFrame {

    private final InfDB idb;
    private final String info;

    /**
     * Creates new form LoginForm
     *
     * @param idb databaskopplingen
     * @param info en sträng som håller information om vilken typ av användare
     * som ska logga in.
     */
    public LoginForm(InfDB idb, String info) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
        this.info = info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblLogoHolder = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        pnlLoginPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 475));
        setSize(new java.awt.Dimension(400, 450));

        pnlBackground.setBackground(new java.awt.Color(29, 29, 48));
        pnlBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlBackground.setLayout(null);

        lblLogoHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/images/miblogo.png"))); // NOI18N
        pnlBackground.add(lblLogoHolder);
        lblLogoHolder.setBounds(90, 100, 220, 116);

        lblTitle.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("MIB SEKTOR SKANDINAVIEN");
        pnlBackground.add(lblTitle);
        lblTitle.setBounds(120, 260, 160, 22);

        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("Användarnamn:");
        pnlBackground.add(lblUser);
        lblUser.setBounds(70, 320, 100, 20);

        lblPass.setForeground(new java.awt.Color(204, 204, 204));
        lblPass.setText("Lösenord:");
        lblPass.setAlignmentY(0.0F);
        pnlBackground.add(lblPass);
        lblPass.setBounds(70, 350, 80, 20);
        pnlBackground.add(txtUserName);
        txtUserName.setBounds(210, 320, 110, 24);

        txtPass.setMinimumSize(new java.awt.Dimension(15, 24));
        txtPass.setPreferredSize(new java.awt.Dimension(15, 24));
        pnlBackground.add(txtPass);
        txtPass.setBounds(210, 350, 110, 24);

        pnlLoginPanel.setBackground(new java.awt.Color(29, 29, 48));
        pnlLoginPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlLoginPanel.setLayout(null);

        btnLogin.setText("Logga in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLoginPanel.add(btnLogin);
        btnLogin.setBounds(170, 70, 90, 24);

        pnlBackground.add(pnlLoginPanel);
        pnlLoginPanel.setBounds(60, 310, 270, 110);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userID = txtUserName.getText();
        /* Följande rader är för att hantera lösenordet
        som skrivs in i ett lösenordsfält och hämtas ut som en array av char.
        Till hjälp skapas ett StringBuilderobjekt för att 
        kunna konvertera arrayen till en sträng*/
        char[] password = txtPass.getPassword();
        StringBuilder sb = new StringBuilder("");
        String convertedPassword = sb.append(password).toString(); //Själva konverteringen
        if (Validering.kollaTextRutaTom(txtUserName) && Validering.kollaHeltal(txtUserName) && Validering.kollaLosenOrd(txtPass)) {
            try {
                ArrayList<String> allusers = idb.fetchColumn("select " + info + "_ID from " + info); //hämtar alla aliens eller alla agenters id:n.
                if (allusers.contains(userID)) {
                    //Hämtar det lagrade lösenordet frÃ¥n databasen.
                    String storedPassword = idb.fetchSingle("select LOSENORD from " + info + " where " + info + "_ID = " + userID);
                    String userName = idb.fetchSingle("select NAMN from " + info + " where " + info + "_ID = " + userID);

                    if (storedPassword.equals(convertedPassword)) {
                        JOptionPane.showMessageDialog(null, "Välkommen " + userName + ". Du har nu loggat in");
                        switch (info) {
                            case "AGENT":
                                User anvandare = new User(idb, userID, "AGENT"); //inloggad användare skapas
                                new UserPage(idb, anvandare).setVisible(true);   
                                this.dispose();
                                break;
                            case "ALIEN":
                                anvandare = new User(idb, userID, "ALIEN");
                                new UserPage(idb,anvandare).setVisible(true);
                                this.dispose();
                                break;
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Fel lösenord, försök igen");
                        txtPass.requestFocusInWindow();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Fel användarnamn, försök igen");
                    txtUserName.requestFocusInWindow();
                }

            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något gick fel");
            }

        }

    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLogoHolder;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlLoginPanel;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
